#!/bin/sh
## last updated 3/10 2013

echo "###_root access check";
touch /root/.accesstest;
if [ -e /root/.accesstest ]; then echo "###_you must NOT be logged in as root to continue"; exit; fi;

hn=`hostname`

# evaluate warren or cope toolchain location
if [ $hn = "ubuntu" ];
    then tcloc="../../toolchains/gcc-linaro-arm-linux-gnueabihf-4.7-2013.01-20130125_linux"; #cause warren is special
    else tcloc="/root/CodeSourcery/Sourcery_G++_Lite"; #everyone else who installs to default locations
fi ;

# did we inclde clean in the command line
if [ "$1" = "clean" ]; then
    cleaning="make ARCH=arm CROSS_COMPILE=$tcloc/bin/arm-none-linux-gnueabi- clean";
    echo "###_clean switch included";
    $cleaning;
    exit;
else
    cleaning="";
fi;

make ARCH=arm odroidx2_android_emmc_defconfig
make ARCH=arm -j6 CROSS_COMPILE=$tcloc/bin/arm-linux-gnueabihf- zImage
make ARCH=arm -j6 CROSS_COMPILE=$tcloc/bin/arm-linux-gnueabihf- modules

./compiledcopy

git log > ../../compiled/currentrelease.txt
tar cvzf ../../"ACA_CarPC3.0-Kernel`date +"%m%d%y%H%M"`".tar.gz ../../compiled/

if [ ! -e ../../ACAKernelsCarPCV3/ ]; then mkdir ../../ACAKernelsCarPCV3 ]; fi;
mv ../../ACA_CarPC3.0* ../../ACAKernelsCarPCV3
